# Generated by Django 4.2.1 on 2023-06-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_customer_user_customer_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='user',
        ),
    ]
