# Generated by Django 4.2.1 on 2023-06-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cart_rename_customer_order_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order_details',
            old_name='user',
            new_name='customer',
        ),
    ]
