# Generated by Django 4.2.1 on 2023-06-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_order_details_cart_items_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='cart_items',
        ),
    ]
